LINAGENT-85: Make comptible with python3
The 2to3 tool modifies to python2 code to make it compatible with python3.
It seems that there is still some problems, that need to be solved, for example:

TypeError: Type str doesn't support the buffers API

appears at the line:
logger.info("%s %s : %s" % (name, pid, r.rstrip('\n')))